import Flean.Operations.RoundIntSig
import Flean.Operations.PolicySoundInstances
import Flean.Operations.Add
import Flean.Operations.Mul
import Flean.Operations.Sub
import Flean.Operations.Div
import Flean.Operations.Sqrt
import Flean.Operations.Exp
import Flean.Operations.ExpTaylor
import Flean.Operations.StickyExtract
import Flean.Operations.StickyTermination
import Flean.Operations.ExpComputableDefs
import Flean.Operations.ExpComputableSound
import Flean.Operations.ExpTermination
import Flean.Operations.ExpComputable
import Flean.Operations.LogTaylor
import Flean.Operations.LogComputableDefs
import Flean.Operations.LogComputableSound
import Flean.Operations.LogTermination
import Flean.Operations.LogComputable
import Flean.Operations.FMA
import Flean.Operations.Sterbenz
import Flean.Operations.MulPow2
import Flean.Operations.ExactInt
import Flean.Operations.ExactIntZero
import Flean.Operations.ExactIntAlgebra
import Flean.Operations.ExactIntBound
import Flean.Operations.ScaledExact
import Flean.Operations.ScaledCorrection
import Flean.Operations.DivPow2
import Flean.Operations.AddErrorRepresentable
import Flean.Operations.Fast2Sum
import Flean.Operations.TwoSum
import Flean.Operations.MulErrorRepresentable
import Flean.Operations.TwoProduct
import Flean.Operations.TwoSum6Op
import Flean.Operations.DoubleDouble
import Flean.Operations.DoubleDoubleSqrt
import Flean.Operations.DoubleDoubleFma
import Flean.Operations.DoubleDoubleSum
import Flean.Operations.DoubleDoubleDot
import Flean.Operations.DoubleDoubleHorner
import Flean.Operations.LogBScaleB
import Flean.Operations.RoundToIntegral
import Flean.Operations.VeltkampSplit
import Flean.Operations.KahanSum
import Flean.Operations.CompensatedSum
import Flean.Operations.PairwiseSum
import Flean.Operations.NeumaierSum
import Flean.Operations.DotProduct
import Flean.Operations.Horner
import Flean.Operations.HornerFMA
import Flean.Operations.DotProductFMA
import Flean.Operations.CompensatedHorner
import Flean.Operations.Clenshaw
import Flean.Operations.GeomBound
import Flean.Operations.AffineFold
import Flean.Operations.AffineFoldInstances
import Flean.Operations.GeneralAccum
import Flean.Operations.ClenshawBound
import Flean.Operations.JetHorner
import Flean.Operations.NewtonHorner
import Flean.Operations.BackwardErrorCore
import Flean.Operations.BackwardError
import Flean.Operations.CompensatedNewton
import Flean.Operations.PolynomialConnection
import Flean.Operations.FpSum
import Flean.Operations.FpDotProduct
import Flean.Operations.FpMatVec
import Flean.Operations.Softmax
import Flean.Operations.Log
import Flean.Operations.LogAdapter
import Flean.Operations.LogSumExp
import Flean.Operations.LogClose
import Flean.Operations.CrossEntropy
import Flean.Operations.LayerNorm
import Flean.Operations.MLP
import Flean.Operations.Lipschitz
import Flean.Operations.LipschitzFp
import Flean.Operations.Activation
import Flean.Operations.Activations.Sigmoid
import Flean.Operations.Activations.SigmoidFp
import Flean.Operations.Activations.SigmoidFpClose
import Flean.Operations.Activations.SigmoidDerivFp
import Flean.Operations.Activations.Tanh
import Flean.Operations.Activations.TanhFp
import Flean.Operations.Activations.TanhFpClose
import Flean.Operations.Activations.TanhDerivFp
import Flean.Operations.Activations.Gelu
import Flean.Operations.Activations.GeluFp
import Flean.Operations.Activations.GeluFpClose
import Flean.Operations.Activations.GeluDerivFp
import Flean.Operations.Activations.GeluDerivFpClose
import Flean.Operations.Activations.GeluLipschitz
import Flean.Operations.Activations.ActivatedMLP2Demos
