import Batteries.Data.Rat
import Mathlib.Order.TypeTags
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.FieldSimp
import Batteries.Data.Rat
import Mathlib.Order.TypeTags
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.FieldSimp
import Mathlib.Algebra.Algebra.Defs
import Mathlib.Algebra.Order.Module.OrderedSMul
import Mathlib.Algebra.Order.Ring.WithTop
import Mathlib.Algebra.Order.Sub.WithTop
import Mathlib.Order.Interval.Set.WithBotTop
import Mathlib.Algebra.Order.Monoid.WithTop
import Mathlib.Tactic.Finiteness
import Mathlib.Data.NNRat.Order
import Mathlib.Data.NNRat.Lemmas
import Mathlib.Algebra.Field.Rat
import Mathlib.Order.WithBot
import Mathlib.Algebra.Order.Archimedean.Basic

-- TODO?
