"""Export Nanda grokked mod-113 checkpoint tensors as Lean PackedMatrix literals.

Each row is packed little-endian: row_nat = sum(word[j] << (32*j)).
T encodes the magnitude bound 2^(T-149): all |w| <= 2^t with T = t + 149.
"""
import torch
import struct
import math

SD = torch.load('large_files/full_run_data.pth', map_location='cpu', weights_only=False)['model']

OUT_DIR = '../Flean/Operations/ModAddNanda'

# (state-dict key, lean name, reshape, doc)
TENSORS = {
    'Embed': [
        ('embed.W_E', 'wE', None, 'Token embedding `W_E` (d_model=128 rows, vocab=114 cols).'),
        ('pos_embed.W_pos', 'wPos', None, 'Positional embedding `W_pos` (3 positions, d_model=128).'),
        ('unembed.W_U', 'wU', None, 'Unembedding `W_U` (d_model=128 rows, vocab=114 cols).'),
    ],
    'Attn': [
        ('blocks.0.attn.W_K', 'wK', (128, 128), 'Attention key weights, heads flattened (4*32=128 rows, d_model=128).'),
        ('blocks.0.attn.W_Q', 'wQ', (128, 128), 'Attention query weights, heads flattened.'),
        ('blocks.0.attn.W_V', 'wV', (128, 128), 'Attention value weights, heads flattened.'),
        ('blocks.0.attn.W_O', 'wO', None, 'Attention output projection (128 x 128).'),
    ],
    'Mlp': [
        ('blocks.0.mlp.W_in', 'wIn', None, 'MLP input weights (d_mlp=512 rows, d_model=128).'),
        ('blocks.0.mlp.b_in', 'bIn', (1, 512), 'MLP input bias (1 x 512).'),
        ('blocks.0.mlp.W_out', 'wOut', None, 'MLP output weights (d_model=128 rows, d_mlp=512).'),
        ('blocks.0.mlp.b_out', 'bOut', (1, 128), 'MLP output bias (1 x 128).'),
    ],
}

def to_words(t):
    """Tensor -> list of rows of uint32 words (bit patterns)."""
    a = t.detach().numpy().astype('float32')
    rows = []
    for r in a:
        rows.append([struct.unpack('<I', struct.pack('<f', x))[0] for x in r])
    return rows

def bound_T(t):
    mx = t.abs().max().item()
    assert mx > 0
    return int(math.ceil(math.log2(mx))) + 149

def pack_row(words):
    n = 0
    for j, w in enumerate(words):
        n |= w << (32 * j)
    return n

def emit(fname, tensors):
    lines = [
        "import Flean.Operations.ModAddNanda.Packed",
        "",
        f"/-! # Nanda grokked mod-113 checkpoint: {fname} tensors",
        "",
        "Generated by `references/export_weights.py` from `full_run_data.pth`",
        "(mainline run, seed 0, epoch 49900). Bit-exact float32 words, row-packed.",
        "-/",
        "",
        "set_option autoImplicit false",
        "set_option maxRecDepth 10000",
        "set_option maxHeartbeats 0",
        "",
        "namespace Flean.ModAddNanda.Weights",
        "",
    ]
    for key, name, reshape, doc in tensors:
        t = SD[key]
        if reshape:
            t = t.reshape(*reshape)
        assert t.ndim == 2
        r, c = t.shape
        T = bound_T(t)
        rows = [pack_row(w) for w in to_words(t)]
        lines.append(f"/-- {doc} `|w| ≤ 2^{T-149}`. -/")
        lines.append(f"def {name} : PackedMatrix {r} {c} {T} := ⟨[")
        for i, n in enumerate(rows):
            sep = ',' if i < len(rows) - 1 else ''
            lines.append(f"  0x{n:x}{sep}")
        lines.append("], by rfl, by decide⟩")
        lines.append("")
    lines.append("end Flean.ModAddNanda.Weights")
    path = f"{OUT_DIR}/{fname}.lean"
    with open(path, 'w') as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {path}: {sum(1 for _ in lines)} lines")

import sys
which = sys.argv[1:] or list(TENSORS)
for fname in which:
    emit(fname, TENSORS[fname])
